#!/bin/bash
# bump.sh — increment patch version, update cache-bust in HTML files,
# write version+SHA into a JS shim, and stage everything for commit.
#
# Usage:
#   ./bump.sh                # increments patch (0.2.0 -> 0.2.1)
#   ./bump.sh minor          # bumps minor (0.2.1 -> 0.3.0)
#   ./bump.sh major          # bumps major (0.3.0 -> 1.0.0)
#
# After this, run `git add -A && git commit && git push`.

set -e
cd "$(dirname "$0")"

VERSION_FILE="VERSION"
[ -f "$VERSION_FILE" ] || echo "0.0.0" > "$VERSION_FILE"

CURRENT=$(cat "$VERSION_FILE" | tr -d '[:space:]')
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
MAJOR=${MAJOR:-0}; MINOR=${MINOR:-0}; PATCH=${PATCH:-0}

case "${1:-patch}" in
  major)  MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor)  MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch|"") PATCH=$((PATCH + 1)) ;;
  *) echo "usage: $0 [major|minor|patch]"; exit 1 ;;
esac

NEW="${MAJOR}.${MINOR}.${PATCH}"
echo "$NEW" > "$VERSION_FILE"

# Cache-bust string: dot-form "X.Y.Z" works fine in URLs
CACHE_V="$NEW"

# Update all HTML cache-bust query strings
# Matches: assets/foo.js?v=ANYTHING and assets/foo.css?v=ANYTHING
for f in *.html; do
  [ -f "$f" ] || continue
  python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys, re
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
src = re.sub(r'(assets/[a-zA-Z0-9_-]+\.(?:js|css))\?v=[^"\'>\s]+',
             lambda m: f"{m.group(1)}?v={version}", src)
with open(fname, 'w') as fh:
    fh.write(src)
PYEOF
done

# Get git short SHA (will be the prior commit; new commit will be different)
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")

# Write version into a JS shim that all pages can read
cat > assets/version.js <<JSEOF
// Auto-generated by bump.sh — DO NOT EDIT MANUALLY
(function(){
  window.HAJJ_VERSION = {
    version: "$NEW",
    sha: "$SHA",
    built_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  };
  // Inject footer badge after DOM ready
  function inject(){
    if (document.getElementById('hajjVersionBadge')) return;
    var el = document.createElement('div');
    el.id = 'hajjVersionBadge';
    el.textContent = 'v' + window.HAJJ_VERSION.version;
    el.title = 'Hajj CAD ' + window.HAJJ_VERSION.version + ' · ' + window.HAJJ_VERSION.sha + '\nBuilt: ' + window.HAJJ_VERSION.built_at;
    el.style.cssText = 'position:fixed; bottom:8px; right:10px; z-index:9999;'
      + ' font:500 10px/1 ui-monospace,SF Mono,Menlo,monospace;'
      + ' color:rgba(255,255,255,0.35); background:rgba(0,0,0,0.4);'
      + ' padding:3px 7px; border-radius:4px; pointer-events:auto;'
      + ' user-select:none; letter-spacing:0.5px;';
    document.body.appendChild(el);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();
JSEOF

# Inject <script src="assets/version.js?v=X"> into each HTML if not present
for f in *.html; do
  [ -f "$f" ] || continue
  if ! grep -q 'assets/version.js' "$f"; then
    # Insert before closing </body> tag
    python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
inject = f'<script src="assets/version.js?v={version}"></script>\n'
if '</body>' in src:
    src = src.replace('</body>', inject + '</body>', 1)
    with open(fname, 'w') as fh:
        fh.write(src)
PYEOF
  else
    # Update cache-bust on existing version.js include
    python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys, re
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
src = re.sub(r'(assets/version\.js)\?v=[^"\'>\s]+',
             lambda m: f"{m.group(1)}?v={version}", src)
with open(fname, 'w') as fh:
    fh.write(src)
PYEOF
  fi
done

echo ""
echo "✓ Bumped to v${NEW}"
echo "  Updated cache-bust on $(ls *.html | wc -l | tr -d ' ') HTML files"
echo "  Wrote assets/version.js"
echo ""
echo "Next: git add -A && git commit -m 'chore(release): v${NEW}' && git push origin main"
