#!/bin/bash
# bump.sh — increment patch version, update cache-bust in test/*.html only.
# Root *.html files are LOCKED at v0.2.18 (the stable release).
# Future development happens at /test/ paths.
#
# Usage:
#   ./bump.sh                # increments patch (0.2.18 -> 0.2.19)
#   ./bump.sh minor          # bumps minor
#   ./bump.sh major          # bumps major

set -e
cd "$(dirname "$0")"

VERSION_FILE="VERSION"
[ -f "$VERSION_FILE" ] || echo "0.0.0" > "$VERSION_FILE"

CURRENT=$(cat "$VERSION_FILE" | tr -d '[:space:]')
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
MAJOR=${MAJOR:-0}; MINOR=${MINOR:-0}; PATCH=${PATCH:-0}

case "${1:-patch}" in
  major)  MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  minor)  MINOR=$((MINOR + 1)); PATCH=0 ;;
  patch|"") PATCH=$((PATCH + 1)) ;;
  *) echo "usage: $0 [major|minor|patch]"; exit 1 ;;
esac

NEW="${MAJOR}.${MINOR}.${PATCH}"
echo "$NEW" > "$VERSION_FILE"
CACHE_V="$NEW"

# Update cache-bust on TEST HTML only (root frozen at v0.2.18-stable)
mkdir -p test
TOUCHED=0
for f in test/*.html; do
  [ -f "$f" ] || continue
  python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys, re
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
src = re.sub(r'(assets/[a-zA-Z0-9_-]+\.(?:js|css))\?v=[^"\'>\s]+',
             lambda m: f"{m.group(1)}?v={version}", src)
with open(fname, 'w') as fh:
    fh.write(src)
PYEOF
  TOUCHED=$((TOUCHED + 1))
done

# Build version shim (used by both root and test — root content frozen,
# but the version shim itself can be updated without touching root HTML)
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")
cat > assets/version.js <<JSEOF
// Auto-generated by bump.sh — DO NOT EDIT MANUALLY
(function(){
  window.HAJJ_VERSION = {
    version: "$NEW",
    sha: "$SHA",
    built_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    channel: (location.pathname.startsWith('/test/') ? 'test' : 'stable')
  };
  function inject(){
    if (document.getElementById('hajjVersionBadge')) return;
    var el = document.createElement('div');
    el.id = 'hajjVersionBadge';
    var ch = window.HAJJ_VERSION.channel;
    el.textContent = (ch === 'test' ? 'TEST · ' : '') + 'v' + window.HAJJ_VERSION.version;
    el.title = 'Hajj CAD ' + window.HAJJ_VERSION.version + ' · ' + window.HAJJ_VERSION.sha + '\nChannel: ' + ch + '\nBuilt: ' + window.HAJJ_VERSION.built_at;
    var bg = (ch === 'test' ? 'rgba(245,158,11,0.5)' : 'rgba(0,0,0,0.4)');
    el.style.cssText = 'position:fixed; bottom:8px; right:10px; z-index:9999;'
      + ' font:500 10px/1 ui-monospace,SF Mono,Menlo,monospace;'
      + ' color:rgba(255,255,255,0.85); background:' + bg + ';'
      + ' padding:3px 7px; border-radius:4px; pointer-events:auto;'
      + ' user-select:none; letter-spacing:0.5px;';
    document.body.appendChild(el);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();
JSEOF

# Add version.js include into TEST HTML only (root already has it, locked)
for f in test/*.html; do
  [ -f "$f" ] || continue
  if ! grep -q 'assets/version.js' "$f"; then
    python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
inject = f'<script src="assets/version.js?v={version}"></script>\n'
if '</body>' in src:
    src = src.replace('</body>', inject + '</body>', 1)
    with open(fname, 'w') as fh:
        fh.write(src)
PYEOF
  else
    python3 - "$f" "$CACHE_V" <<'PYEOF'
import sys, re
fname, version = sys.argv[1], sys.argv[2]
with open(fname) as fh:
    src = fh.read()
src = re.sub(r'(assets/version\.js)\?v=[^"\'>\s]+',
             lambda m: f"{m.group(1)}?v={version}", src)
with open(fname, 'w') as fh:
    fh.write(src)
PYEOF
  fi
done

echo ""
echo "✓ Bumped to v${NEW}"
echo "  Touched $TOUCHED HTML files in test/ (root LOCKED at v0.2.18-stable)"
echo "  Wrote assets/version.js with channel detection"
